#!/usr/bin/env bash

# Download an apk from the latest artifact of the production branch
# @param $1 a path to save the apk

set -o pipefail
set -eu

download_latest_apk() {
  local -r save_to="$1"
  local apk_url=$(curl -sL "https://droidkaigi2019-dev/app/circleci/apk/feature?year=2019&job_name=assemble_apk" | jq -r ".[0]")

  if [[ -n "$apk_url" ]]; then
    curl -o "${save_to}" "${apk_url}?circle-token=${CIRCLECI_TOKEN}"
  fi
}

download_latest_apk "$1"
